set-option -sa terminal-overrides ",xterm*:Tc"
set -as terminal-features ',xterm-kitty:RGB'
set -g mouse on

# Quality of life
set -g history-limit 50000
set -sg escape-time 0
set -g focus-events on
set -g set-clipboard on
set -g allow-passthrough on
set -g status-position bottom

# Unbind default prefix (Ctrl-b)
unbind C-b

# Set new prefix to Ctrl-Space
set-option -g prefix C-Space

# Allow sending Ctrl-Space to nested sessions or applications
bind-key C-Space send-prefix

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded"

# Vim style pane selection
bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

# Resize panes (repeatable)
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Move windows left/right (repeatable)
bind -r < swap-window -d -t -1
bind -r > swap-window -d -t +1

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-and-cancel

bind 'i' split-window -v -c "#{pane_current_path}"
bind 'e' split-window -h -c "#{pane_current_path}"

bind 'n' new-session -c "#{pane_current_path}"
bind 'c' new-window -c "#{pane_current_path}"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-open'

set -g @tokyo-night-tmux_window_id_style fsquare

# Keep at the very bottom
run '~/.config/tmux/plugins/tpm/tpm'
